export const themes = {
  bds: {
    1: { name: "cover", img: "./source/img/bds/logo.jpg" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: { name: "Andy", img: "./source/img/bds/andy.jpg" },
    4: { name: "Dano", img: "./source/img/bds/dano.jpg" },
    5: { name: "Danča", img: "./source/img/bds/danca.jpg" },
    6: { name: "Fero", img: "./source/img/bds/fero.jpg" },
    7: { name: "Miro", img: "./source/img/bds/miro.jpg" },
    8: { name: "Pitkin", img: "./source/img/bds/pitkin.jpg" },
    9: { name: "Wahe", img: "./source/img/bds/wahe.jpg" },
    10: { name: "Oli", img: "./source/img/bds/oli.jpg" },
    11: { name: "Máka", img: "./source/img/bds/maka.jpg" },
    12: { name: "Káka", img: "./source/img/bds/kaka.jpg" },
    language: "english",
  },
  lili: {
    1: { name: "cover", img: "./source/img/lili/logo.png" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: {
      name: "Naty/Luky/Jirka",
      img: "./source/img/lili/martaNatyLukyJirka.jpeg",
    },
    4: { name: "Mateo", img: "./source/img/lili/mateo.jpeg" },
    5: {
      name: "Milan/Mateo/Lili",
      img: "./source/img/lili/milanMateoLili.jpeg",
    },
    6: { name: "Nikol/Stázi/Tom", img: "./source/img/lili/nikolStaziTom.jpeg" },
    7: { name: "Petr/Líba", img: "./source/img/lili/petrLiba.jpeg" },
    8: { name: "Tomáš", img: "./source/img/lili/tomas.jpeg" },
    9: { name: "Stázinka", img: "./source/img/lili/stazinka.jpeg" },
    10: {
      name: "Tom/Stázi/Tobiáš",
      img: "./source/img/lili/tomStaziTobias.jpeg",
    },
    11: { name: "Líba", img: "./source/img/lili/liba.jpeg" },
    12: { name: "Lili", img: "./source/img/lili/lili.jpeg" },
    language: "czech",
  },
  gfa: {
    1: { name: "cover", img: "./source/img/gfa/logo.png" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: { name: "Ivana", img: "./source/img/gfa/ivana.png" },
    4: { name: "Lukáš J.", img: "./source/img/gfa/lukasj.png" },
    5: { name: "Lukáš K.", img: "./source/img/gfa/lukask.png" },
    6: { name: "Matěj", img: "./source/img/gfa/matej.png" },
    7: { name: "mentor1", img: "./source/img/gfa/mentor1.png" },
    8: { name: "mentor2", img: "./source/img/gfa/mentor2.png" },
    9: { name: "Pavla", img: "./source/img/gfa/pavla.png" },
    10: { name: "psy", img: "./source/img/gfa/psy.png" },
    11: { name: "Aleš", img: "./source/img/gfa/ales.png" },
    12: { name: "Dávid", img: "./source/img/gfa/david.png" },
    language: "english",
  },
  rebenka: {
    1: { name: "cover", img: "./source/img/rebenka/cover.jpg" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: { name: "dedko", img: "./source/img/rebenka/dedko.jpg" },
    4: { name: "deko", img: "./source/img/rebenka/deko.jpg" },
    5: { name: "dusan", img: "./source/img/rebenka/dusan.jpg" },
    6: { name: "janko", img: "./source/img/rebenka/janko.jpg" },
    7: { name: "manka", img: "./source/img/rebenka/manka.jpg" },
    8: { name: "rebeka", img: "./source/img/rebenka/rebeka.JPG" },
    9: { name: "tatik", img: "./source/img/rebenka/tatik.jpg" },
    10: { name: "baki", img: "./source/img/rebenka/baki.jpg" },
    11: { name: "babka", img: "./source/img/rebenka/babka.jpg" },
    12: { name: "dano", img: "./source/img/rebenka/dano.jpg" },
    language: "english",
  },
  nature: {
    1: { name: "cover", img: "./source/img/nature/nature.png" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: { name: "tree", img: "./source/img/nature/tree.jpg" },
    4: { name: "flower", img: "./source/img/nature/flower.jpg" },
    5: { name: "mountain", img: "./source/img/nature/mountain.jpg" },
    6: { name: "river", img: "./source/img/nature/river.jpg" },
    7: { name: "clouds", img: "./source/img/nature/clouds.jpg" },
    8: { name: "stars", img: "./source/img/nature/stars.jpg" },
    9: { name: "drop", img: "./source/img/nature/drop.jpg" },
    10: { name: "leaf", img: "./source/img/nature/leaf.jpg" },
    11: { name: "sun", img: "./source/img/nature/sun.jpg" },
    12: { name: "moon", img: "./source/img/nature/moon.jpg" },
    language: "english",
  },
  detib: {
    1: { name: "", img: "./source/img/detib/logo.jpg" },
    2: { name: "", img: "./source/img/blank.png" },
    3: { name: "", img: "./source/img/detib/3.jpg" },
    4: { name: "", img: "./source/img/detib/4.jpg" },
    5: { name: "", img: "./source/img/detib/5.jpg" },
    6: { name: "", img: "./source/img/detib/6.jpg" },
    7: { name: "", img: "./source/img/detib/7.jpg" },
    8: { name: "", img: "./source/img/detib/8.jpg" },
    9: { name: "", img: "./source/img/detib/9.jpg" },
    10: { name: "", img: "./source/img/detib/10.jpg" },
    11: { name: "", img: "./source/img/detib/1.jpg" },
    12: { name: "", img: "./source/img/detib/2.jpg" },
    language: "english",
  },
  animals: {
    1: { name: "cover", img: "./source/img/animals/footprints.jpg" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: { name: "rabbit", img: "./source/img/animals/rabbit.jpg" },
    4: { name: "elephant", img: "./source/img/animals/elephant.jpg" },
    5: { name: "gorilla", img: "./source/img/animals/gorilla.jpg" },
    6: { name: "hippo", img: "./source/img/animals/hippo.jpg" },
    7: { name: "lion", img: "./source/img/animals/lion.jpg" },
    8: { name: "panda", img: "./source/img/animals/panda.jpg" },
    9: { name: "penguin", img: "./source/img/animals/penguin.jpg" },
    10: { name: "tiger", img: "./source/img/animals/tiger.jpg" },
    11: { name: "Bear", img: "./source/img/animals/bear.jpg" },
    12: { name: "dog", img: "./source/img/animals/dog.jpg" },
    language: "english",
  },
  legends: {
    language: "english",
    1: { name: "cover", img: "./source/img/legends/cover.jpg" },
    2: { name: "done", img: "./source/img/blank.png" },
    3: { name: "2Pac", img: "./source/img/legends/2Pac.jpeg" },
    4: { name: "Biggie", img: "./source/img/legends/biggie.jpeg" },
    5: { name: "Bolt", img: "./source/img/legends/bolt.jpeg" },
    6: { name: "einstein", img: "./source/img/legends/einstein.jpg" },
    7: { name: "Gretzky", img: "./source/img/legends/gretzky.jpeg" },
    8: { name: "Jackson", img: "./source/img/legends/jackson.jpg" },
    9: { name: "Jobs", img: "./source/img/legends/jobs.jpeg" },
    10: { name: "Jordan", img: "./source/img/legends/jordan.jpg" },
    11: { name: "Ledecka", img: "./source/img/legends/ledecka.jpg" },
    12: { name: "Zatopek", img: "./source/img/legends/zatopek.jpeg" },
  },
};
