const languages = {
  english: {
    prompt: "Please enter code.",
    player1: "Player 1",
    player2: "Player 2",
    playerSolo: "Player X",
    submit: "Submit",
    wins: "wins",
    youGo: "you go",
    theChamp: "WINNER",
    playAgain: "Play Again",
    tie: "tie",
  },
  czech: {
    prompt: "Prosím zadejte kód.",
    player1: "Hráč 1",
    player2: "Hráč 2",
    playerSolo: "Hráč X",
    submit: "Odeslat",
    wins: "výhry",
    youGo: "na tahu",
    theChamp: "VÍTĚZ",
    playAgain: "Hrát znovu",
    tie: "remíza",
  },
};
