const themes = {
  bds: {
    1: { name: "Máka", img: "./source/bds/maka.jpg" },
    2: { name: "Káka", img: "./source/bds/kaka.jpg" },
    3: { name: "Andy", img: "./source/bds/andy.jpg" },
    4: { name: "Dano", img: "./source/bds/dano.jpg" },
    5: { name: "Danča", img: "./source/bds/danca.jpg" },
    6: { name: "Fero", img: "./source/bds/fero.jpg" },
    7: { name: "Miro", img: "./source/bds/miro.jpg" },
    8: { name: "Pitkin", img: "./source/bds/pitkin.jpg" },
    9: { name: "Wahe", img: "./source/bds/wahe.jpg" },
    10: { name: "Oli", img: "./source/bds/oli.jpg" },
    11: { name: "cover", img: "./source/bds/logo.jpg" },
    12: { name: "done", img: "./source/bds/blank.png" },
    language: "english",
  },
  lili: {
    1: { name: "Líba", img: "./source/lili/liba.jpeg" },
    2: { name: "Lili", img: "./source/lili/lili.jpeg" },
    3: {
      name: "Naty/Luky/Jirka",
      img: "./source/lili/martaNatyLukyJirka.jpeg",
    },
    4: { name: "Mateo", img: "./source/lili/mateo.jpeg" },
    5: { name: "Milan/Mateo/Lili", img: "./source/lili/milanMateoLili.jpeg" },
    6: { name: "Nikol/Stázi/Tom", img: "./source/lili/nikolStaziTom.jpeg" },
    7: { name: "Petr/Líba", img: "./source/lili/petrLiba.jpeg" },
    8: { name: "Tomáš", img: "./source/lili/tomas.jpeg" },
    9: { name: "Stázinka", img: "./source/lili/stazinka.jpeg" },
    10: { name: "Tom/Stázi/Tobiáš", img: "./source/lili/tomStaziTobias.jpeg" },
    11: { name: "cover", img: "./source/lili/logo.jpg" },
    12: { name: "done", img: "./source/lili/blank.png" },
    language: "czech",
  },
  gfa: {
    1: { name: "Aleš", img: "./source/gfa/ales.png" },
    2: { name: "Dávid", img: "./source/gfa/david.png" },
    3: { name: "Ivana", img: "./source/gfa/ivana.png" },
    4: { name: "Lukáš J.", img: "./source/gfa/lukasj.png" },
    5: { name: "Lukáš K.", img: "./source/gfa/lukask.png" },
    6: { name: "Matěj", img: "./source/gfa/matej.png" },
    7: { name: "mentor1", img: "./source/gfa/mentor1.png" },
    8: { name: "mentor2", img: "./source/gfa/mentor2.png" },
    9: { name: "Pavla", img: "./source/gfa/pavla.png" },
    10: { name: "psy", img: "./source/gfa/psy.png" },
    11: { name: "cover", img: "./source/gfa/logo.png" },
    12: { name: "done", img: "./source/gfa/blank.png" },
    language: "english",
  },
  rebenka: {
    1: { name: "babka", img: "./source/rebenka/babka.jpg" },
    2: { name: "dano", img: "./source/rebenka/dano.jpg" },
    3: { name: "dedko", img: "./source/rebenka/dedko.jpg" },
    4: { name: "deko", img: "./source/rebenka/deko.jpg" },
    5: { name: "dusan", img: "./source/rebenka/dusan.jpg" },
    6: { name: "janko", img: "./source/rebenka/janko.jpg" },
    7: { name: "manka", img: "./source/rebenka/manka.jpg" },
    8: { name: "rebeka", img: "./source/rebenka/rebeka.JPG" },
    9: { name: "tatik", img: "./source/rebenka/tatik.jpg" },
    10: { name: "baki", img: "./source/rebenka/baki.jpg" },
    11: { name: "cover", img: "./source/rebenka/cover.jpg" },
    12: { name: "done", img: "./source/rebenka/blank.png" },
    language: "english",
  },
  hallo: {},
};
