const themes = {
  bds: {
    1: { name: "Máka", img: "./source/bds/maka.jpg" },
    2: { name: "Káka", img: "./source/bds/kaka.jpg" },
    3: { name: "Andy", img: "./source/bds/andy.jpg" },
    4: { name: "Dano", img: "./source/bds/dano.jpg" },
    5: { name: "Danča", img: "./source/bds/danca.jpg" },
    6: { name: "Fero", img: "./source/bds/fero.jpg" },
    7: { name: "Miro", img: "./source/bds/miro.jpg" },
    8: { name: "Pitkin", img: "./source/bds/pitkin.jpg" },
    9: { name: "Wahe", img: "./source/bds/wahe.jpg" },
    10: { name: "Oli", img: "./source/bds/oli.jpg" },
    11: { name: "cover", img: "./source/bds/logo.jpg" },
    12: { name: "done", img: "./source/blank.png" },
    language: "english",
  },
  lili: {
    1: { name: "Líba", img: "./source/lili/liba.jpeg" },
    2: { name: "Lili", img: "./source/lili/lili.jpeg" },
    3: {
      name: "Naty/Luky/Jirka",
      img: "./source/lili/martaNatyLukyJirka.jpeg",
    },
    4: { name: "Mateo", img: "./source/lili/mateo.jpeg" },
    5: { name: "Milan/Mateo/Lili", img: "./source/lili/milanMateoLili.jpeg" },
    6: { name: "Nikol/Stázi/Tom", img: "./source/lili/nikolStaziTom.jpeg" },
    7: { name: "Petr/Líba", img: "./source/lili/petrLiba.jpeg" },
    8: { name: "Tomáš", img: "./source/lili/tomas.jpeg" },
    9: { name: "Stázinka", img: "./source/lili/stazinka.jpeg" },
    10: { name: "Tom/Stázi/Tobiáš", img: "./source/lili/tomStaziTobias.jpeg" },
    11: { name: "cover", img: "./source/lili/logo.jpg" },
    12: { name: "done", img: "./source/blank.png" },
    language: "czech",
  },
  gfa: {
    1: { name: "Aleš", img: "./source/gfa/ales.png" },
    2: { name: "Dávid", img: "./source/gfa/david.png" },
    3: { name: "Ivana", img: "./source/gfa/ivana.png" },
    4: { name: "Lukáš J.", img: "./source/gfa/lukasj.png" },
    5: { name: "Lukáš K.", img: "./source/gfa/lukask.png" },
    6: { name: "Matěj", img: "./source/gfa/matej.png" },
    7: { name: "mentor1", img: "./source/gfa/mentor1.png" },
    8: { name: "mentor2", img: "./source/gfa/mentor2.png" },
    9: { name: "Pavla", img: "./source/gfa/pavla.png" },
    10: { name: "psy", img: "./source/gfa/psy.png" },
    11: { name: "cover", img: "./source/gfa/logo.png" },
    12: { name: "done", img: "./source/blank.png" },
    language: "english",
  },
  rebenka: {
    1: { name: "babka", img: "./source/rebenka/babka.jpg" },
    2: { name: "dano", img: "./source/rebenka/dano.jpg" },
    3: { name: "dedko", img: "./source/rebenka/dedko.jpg" },
    4: { name: "deko", img: "./source/rebenka/deko.jpg" },
    5: { name: "dusan", img: "./source/rebenka/dusan.jpg" },
    6: { name: "janko", img: "./source/rebenka/janko.jpg" },
    7: { name: "manka", img: "./source/rebenka/manka.jpg" },
    8: { name: "rebeka", img: "./source/rebenka/rebeka.JPG" },
    9: { name: "tatik", img: "./source/rebenka/tatik.jpg" },
    10: { name: "baki", img: "./source/rebenka/baki.jpg" },
    11: { name: "cover", img: "./source/rebenka/cover.jpg" },
    12: { name: "done", img: "./source/blank.png" },
    language: "english",
  },
  nature: {
    1: { name: "sun", img: "./source/nature/sun.jpg" },
    2: { name: "moon", img: "./source/nature/moon.jpg" },
    3: { name: "tree", img: "./source/nature/tree.jpg" },
    4: { name: "flower", img: "./source/nature/flower.jpg" },
    5: { name: "mountain", img: "./source/nature/mountain.jpg" },
    6: { name: "river", img: "./source/nature/river.jpg" },
    7: { name: "clouds", img: "./source/nature/clouds.jpg" },
    8: { name: "stars", img: "./source/nature/stars.jpg" },
    9: { name: "drop", img: "./source/nature/drop.jpg" },
    10: { name: "leaf", img: "./source/nature/leaf.jpg" },
    11: { name: "cover", img: "./source/nature/nature.png" },
    12: { name: "done", img: "./source/blank.png" },
    language: "english",
  },
  legends: {
    1: { name: "2Pac", img: "./source/legends/2Pac.jpeg" },
    2: { name: "Biggie", img: "./source/legends/biggie.jpeg" },
    3: { name: "Bolt", img: "./source/legends/bolt.jpeg" },
    4: { name: "Einstein", img: "./source/legends/Einstein.jpeg" },
    5: { name: "Gretzky", img: "./source/legends/gretzky.jpeg" },
    6: { name: "Jackson", img: "./source/legends/jackson.jpeg" },
    7: { name: "Jobs", img: "./source/legends/jobs.jpeg" },
    8: { name: "Jordan", img: "./source/legends/jordan.jpeg" },
    9: { name: "Ledecka", img: "./source/legends/ledecka.jpeg" },
    10: { name: "Zatopek", img: "./source/legends/zatopek.jpeg" },
    11: { name: "cover", img: "./source/legends/cover.jpg" },
    12: { name: "done", img: "./source/blank.png" },
    language: "english",
  },
  animals: {
    1: { name: "Bear", img: "./source/animals/bear.jpg" },
    2: { name: "dog", img: "./source/animals/dog.jpg" },
    3: { name: "dolphin", img: "./source/animals/dolphin.jpg" },
    4: { name: "elephant", img: "./source/animals/elephant.jpg" },
    5: { name: "gorilla", img: "./source/animals/gorilla.jpg" },
    6: { name: "hippo", img: "./source/animals/hippo.jpg" },
    7: { name: "lion", img: "./source/animals/lion.jpg" },
    8: { name: "panda", img: "./source/animals/panda.jpg" },
    9: { name: "penguin", img: "./source/animals/penguin.jpg" },
    10: { name: "tiger", img: "./source/animals/tiger.jpg" },
    11: { name: "cover", img: "./source/animals/footprints.jpg" },
    12: { name: "done", img: "./source/blank.png" },
    language: "english",
  },
};
